---
namespace: ednz_cloud
name: hashistack
version: 0.13.5
readme: README.md
authors:
  - Bertrand Lanson <bertrand.lanson@protonmail.com>
description: your collection description
license: ["MIT"]
license_file: "LICENSE"
tags: ["tools", "hashicorp", "nomad", "vault", "consul"]
dependencies: {}
repository: https://gitlab.ednz.fr/ednz-cloud/ansible/collections/ednz_cloud.hashistack
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker
build_ignore: []
