---
roles: []
collections:
  - name: ssh://git@gitlab.ednz.fr:2022/ednz-cloud/ansible/collections/ednz_cloud.utils.git
    type: git
    version: v0.11.1
  - name: community.crypto
    version: 3.0.4
  - name: openstack.cloud
    version: 2.5.0
