---
roles: []
collections:
  - name: https://github.com/ednz-cloud/ansible-collection-utils.git
    type: git
    version: v0.11.3
  - name: community.crypto
    version: 3.1.1
  - name: openstack.cloud
    version: 2.5.0
