---
roles: []
collections:
  - name: https://github.com/ednz-cloud/ansible-collection-utils.git
    type: git
    version: v0.11.0
  - name: community.crypto
    version: 3.0.4
  - name: openstack.cloud
    version: 2.5.0
