---
- name: "common | configure_etc_hosts | Add consul internal DNS entries"
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED: {{ hashistack_consul_internal_name }}"
    block: |
      {% for host in (groups['consul_servers'] | default([])) %}
      {{ hostvars[host].api_interface_address }} {{ hashistack_consul_internal_name }}
      {% endfor %}
  when: enable_consul | bool

- name: "common | configure_etc_hosts | Add vault internal DNS entries"
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED: {{ hashistack_vault_internal_name }}"
    block: |
      {% for host in (groups['vault_servers'] | default([])) %}
      {{ hostvars[host].api_interface_address }} {{ hashistack_vault_internal_name }}
      {% endfor %}
  when: enable_vault | bool

- name: "common | configure_etc_hosts | Add nomad internal DNS entries"
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED: {{ hashistack_nomad_internal_name }}"
    block: |
      {% for host in (groups['nomad_servers'] | default([])) %}
      {{ hostvars[host].api_interface_address }} {{ hashistack_nomad_internal_name }}
      {% endfor %}
  when: enable_nomad | bool
