---
- name: Include credentials generation playbook
  ansible.builtin.import_playbook: ednz_cloud.hashistack.credentials.yml
  vars:
    hashistack_configuration_directory: "{{ molecule_scenario_directory }}/etc/hashistack"

- name: Include bootstrap playbook
  ansible.builtin.import_playbook: ednz_cloud.hashistack.bootstrap.yml
  vars:
    hashistack_configuration_directory: "{{ molecule_scenario_directory }}/etc/hashistack"

- name: Include preflight playbook
  ansible.builtin.import_playbook: ednz_cloud.hashistack.preflight.yml
  vars:
    hashistack_configuration_directory: "{{ molecule_scenario_directory }}/etc/hashistack"
