---
platforms:
  - name: nomad-server.ednz.fr
    description: Molecule test instance.
    flavor: a2-ram4-disk20-perf1
    image: ${MOLECULE_TEST_OS:-"Debian 13 trixie"}
    user: ${MOLECULE_TEST_USER:-"debian"}
    auto_ip: false
    network:
      name: pcp-w3rxsrj-backend-network
      create: false
    security_group:
      name: molecule__nomad_cluster__tls_multi_node__openstack
      create: true
      description: Molecule test security group.
      rules:
        - proto: tcp
          port: -1
          port_min: 0
          port_max: 0
          cidr: 0.0.0.0/0
          type: IPv4
    groups:
      - deployment
      - common
      - nomad_servers
      - nomad_clients
      - consul_servers # to pass preflight only
      - vault_servers # to pass preflight only
      - consul_agents # to pass preflight only
scenario:
  name: nomad_cluster__tls_single_node__openstack
