---
- name: Include verify
  ansible.builtin.import_playbook: ednz_cloud.hashistack.molecule_verify.yml
  vars:
    hashistack_configuration_directory: "{{ molecule_scenario_directory }}/etc/hashistack"
